---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: advent-of-code
  name: puzzles.advent-of-code.wttj.co
spec:
  group: advent-of-code.wttj.co
  names:
    kind: Puzzle
    plural: puzzles
    singular: puzzle
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Day of the puzzle
          jsonPath: .spec.day
          name: day
          type: integer
        - description: Year of the puzzle
          jsonPath: .spec.year
          name: year
          type: integer
        - description: Resolution status
          jsonPath: .status.solved
          name: solved
          type: boolean
      deprecationWarning:
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                day:
                  type: integer
                input:
                  type: string
                year:
                  type: integer
              type: object
            status:
              properties:
                observedGeneration:
                  type: integer
                solved:
                  type: boolean
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
