---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: advent-of-code
  name: results.advent-of-code.wttj.co
spec:
  group: advent-of-code.wttj.co
  names:
    kind: Result
    plural: results
    singular: result
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Day of the puzzle
          jsonPath: .spec.day
          name: day
          type: integer
        - description: Year of the puzzle
          jsonPath: .spec.year
          name: year
          type: integer
        - description: First part result
          jsonPath: .spec.firstPart
          name: firstPart
          type: integer
        - description: Second part result
          jsonPath: .spec.secondPart
          name: secondPart
          type: integer
      deprecationWarning:
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                day:
                  type: integer
                firstPart:
                  type: integer
                secondPart:
                  type: integer
                year:
                  type: integer
              type: object
            status:
              properties:
                observedGeneration:
                  type: integer
                solved:
                  type: boolean
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
