# Default values for advent-of-code.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: pauldnwttj/advent-of-code-operator
  tag: v0.0.1-alpha
  pullPolicy: Always
resources:
   limits:
    cpu: 100m
    memory: 256Mi
   requests:
    cpu: 100m
    memory: 256Mi
namespace: advent-of-code
