---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: advent-of-code
  name: advent-of-code
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - '*'
  - apiGroups:
      - advent-of-code.wttj.co
    resources:
      - results
    verbs:
      - '*'
  - apiGroups:
      - advent-of-code.wttj.co
    resources:
      - results/status
    verbs:
      - '*'
  - apiGroups:
      - advent-of-code.wttj.co
    resources:
      - puzzles
    verbs:
      - '*'
  - apiGroups:
      - advent-of-code.wttj.co
    resources:
      - puzzles/status
    verbs:
      - '*'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: advent-of-code
  name: advent-of-code
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: advent-of-code
  name: advent-of-code
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: advent-of-code
subjects:
  - kind: ServiceAccount
    name: advent-of-code
    namespace: {{ .Values.namespace }}
